// AnimBP2FPExportCommandlet.cpp - Commandlet Implementation
// Copyright (c) 2026 OpenClaw Research. All Rights Reserved.

#include "AnimBP2FPExportCommandlet.h"
#include "AnimBPExporter.h"
#include "FBP2FPMappingRegistry.h"
#include "Animation/AnimBlueprint.h"
#include "AssetRegistry/ARFilter.h"
#include "AssetRegistry/AssetRegistryModule.h"
#include "Misc/FileHelper.h"
#include "Misc/Paths.h"
#include "Misc/Parse.h"
#include "HAL/FileManager.h"

UAnimBP2FPExportCommandlet::UAnimBP2FPExportCommandlet()
{
	IsClient = false;
	IsEditor = true;
	IsServer = false;
	LogToConsole = true;
}

int32 UAnimBP2FPExportCommandlet::Main(const FString& Params)
{
	UE_LOG(LogTemp, Log, TEXT("=== AnimBP2FP Export Commandlet Starting ==="));
	
	// Output directory: unified convention {Project}/Saved/BP2DSL/AnimBP
	FString OutputDir = FPaths::ProjectDir() / TEXT("Saved") / TEXT("BP2DSL") / TEXT("AnimBP");
	if (!IFileManager::Get().DirectoryExists(*OutputDir))
	{
		IFileManager::Get().MakeDirectory(*OutputDir, true);
	}
	
	// Find all AnimBlueprints via AssetRegistry
	FAssetRegistryModule& AssetRegistryModule = FModuleManager::LoadModuleChecked<FAssetRegistryModule>("AssetRegistry");
	IAssetRegistry& AssetRegistry = AssetRegistryModule.Get();
	
	// Ensure asset registry is fully loaded
	AssetRegistry.SearchAllAssets(true);
	
	FString AssetRoot = TEXT("/Game");
	FString ExactAssetPath;
	FParse::Value(*Params, TEXT("AssetRoot="), AssetRoot);
	FParse::Value(*Params, TEXT("AssetPath="), ExactAssetPath);
	const bool bAllowUnsupported = FParse::Param(*Params, TEXT("AllowUnsupported"));
	if (!AssetRoot.StartsWith(TEXT("/Game")) || AssetRoot.Contains(TEXT("..")))
	{
		UE_LOG(LogTemp, Error, TEXT("Invalid -AssetRoot='%s'; AnimBP2FP commandlet only exports /Game content"), *AssetRoot);
		return 1;
	}

	TArray<FAssetData> AnimBPAssets;
	FARFilter Filter;
	Filter.ClassPaths.Add(UAnimBlueprint::StaticClass()->GetClassPathName());
	Filter.PackagePaths.Add(FName(*AssetRoot));
	Filter.bRecursivePaths = true;
	AssetRegistry.GetAssets(Filter, AnimBPAssets);
	if (!ExactAssetPath.IsEmpty())
	{
		AnimBPAssets.RemoveAll([&ExactAssetPath](const FAssetData& AssetData)
		{
			return AssetData.PackageName.ToString() != ExactAssetPath
				&& AssetData.GetObjectPathString() != ExactAssetPath;
		});
	}
	
	UE_LOG(LogTemp, Log, TEXT("Found %d Animation Blueprints"), AnimBPAssets.Num());
	
	if (AnimBPAssets.Num() == 0)
	{
		UE_LOG(LogTemp, Warning, TEXT("No Animation Blueprints found!"));
		return 1;
	}
	
	int32 SuccessCount = 0;
	int32 FailCount = 0;
	FString AllOutput;
	
	for (const FAssetData& AssetData : AnimBPAssets)
	{
		FString AssetName = AssetData.AssetName.ToString();
		FString PackagePath = AssetData.PackageName.ToString();
		FString ObjectPath = AssetData.GetObjectPathString();
		
		UE_LOG(LogTemp, Log, TEXT("Processing: %s (%s)"), *AssetName, *PackagePath);
		
		// Load the animation blueprint
		UAnimBlueprint* AnimBP = Cast<UAnimBlueprint>(AssetData.GetAsset());
		if (!AnimBP)
		{
			UE_LOG(LogTemp, Warning, TEXT("  FAILED to load: %s"), *AssetName);
			FailCount++;
			continue;
		}
		
		// Export
		FAnimBPExporter::FExportOptions Options;
		Options.bPrettyPrint = true;
		Options.IndentSize = 2;
		
		FString DSLOutput = FAnimBPExporter::ExportWithOptions(AnimBP, Options);
		const bool bExportError = DSLOutput.TrimStart().StartsWith(TEXT("; Error:"));
		const bool bUnsupported = DSLOutput.Contains(TEXT(":coverage unsupported"));
		if (bExportError || (bUnsupported && !bAllowUnsupported))
		{
			UE_LOG(LogTemp, Error, TEXT("  FAILED semantic export: %s%s"), *AssetName,
				bUnsupported ? TEXT(" (contains unsupported animation-node semantics; use -AllowUnsupported only for diagnostics)") : TEXT(""));
			FailCount++;
			continue;
		}
		
		// File header
		FString FileContent = FString::Printf(
			TEXT(";; AnimLang DSL Export\n")
			TEXT(";; Source: %s\n")
			TEXT(";; Asset: %s\n")
			TEXT(";; Generated by AnimBP2FP Plugin\n")
			TEXT(";;\n\n")
			TEXT("%s\n"),
			*PackagePath, *AssetName, *DSLOutput
		);
		
		// Use unified path convention via mapping registry
		FString FullPath = AnimBP->GetPathName();
		FString OutputFilePath = FBP2FPMappingRegistry::BlueprintToDSLPath(FullPath, TEXT("AnimBP"), TEXT(".animlang"));
		if (OutputFilePath.IsEmpty())
		{
			UE_LOG(LogTemp, Warning, TEXT("  Cannot resolve DSL path for: %s"), *AssetName);
			FailCount++;
			continue;
		}

		// Ensure directory exists
		FString Dir = FPaths::GetPath(OutputFilePath);
		if (!IFileManager::Get().DirectoryExists(*Dir))
		{
			IFileManager::Get().MakeDirectory(*Dir, true);
		}

		if (FFileHelper::SaveStringToFile(FileContent, *OutputFilePath, FFileHelper::EEncodingOptions::ForceUTF8WithoutBOM))
		{
			UE_LOG(LogTemp, Log, TEXT("  OK -> %s"), *OutputFilePath);
			SuccessCount++;
		}
		else
		{
			UE_LOG(LogTemp, Error, TEXT("  FAILED to write: %s"), *OutputFilePath);
			FailCount++;
		}
		
		// Print DSL to console for review
		UE_LOG(LogTemp, Log, TEXT("--- DSL Output for %s ---"), *AssetName);
		UE_LOG(LogTemp, Log, TEXT("%s"), *DSLOutput);
		UE_LOG(LogTemp, Log, TEXT("--- End DSL Output ---"));
		
		AllOutput += FString::Printf(TEXT("\n;; ======== %s ========\n"), *AssetName);
		AllOutput += DSLOutput;
		AllOutput += TEXT("\n");
	}
	
	// Write combined file
	FString CombinedPath = OutputDir / TEXT("_all_animbp.animlang");
	FString CombinedContent = FString::Printf(
		TEXT(";; AnimLang DSL - All Animation Blueprints\n")
		TEXT(";; Total: %d exported, %d failed\n")
		TEXT(";;\n\n")
		TEXT("%s"),
		SuccessCount, FailCount, *AllOutput
	);
	FFileHelper::SaveStringToFile(CombinedContent, *CombinedPath, FFileHelper::EEncodingOptions::ForceUTF8WithoutBOM);
	
	UE_LOG(LogTemp, Log, TEXT("=== Export Complete: %d/%d succeeded. Output: %s ==="), 
		SuccessCount, AnimBPAssets.Num(), *OutputDir);
	
	return (FailCount > 0) ? 1 : 0;
}
